debian: Use consistent whitespace
When in doubt, follow upstream's coding style:

  * use spaces for both indentation an alignment;

  * don't use tabs except where make requires them;

  * don't attempt to align the backslashes used to make a variable
    declaration or shell snipped span multiple lines.

This commit is better viewed with 'git show -w'.

diff --git a/debian/libvirt-daemon-system.postrm b/debian/libvirt-daemon-system.postrm
--- a/debian/libvirt-daemon-system.postrm
+++ b/debian/libvirt-daemon-system.postrm
@@ -21,44 +21,43 @@ set -e
 
 case "$1" in
     purge)
-    	if getent group libvirt >/dev/null; then
-    		delgroup libvirt >/dev/null || true
-	fi
+        if getent group libvirt >/dev/null; then
+            delgroup libvirt >/dev/null || true
+        fi
 
-    	if getent passwd libvirt-qemu >/dev/null; then
-    		deluser libvirt-qemu >/dev/null || true
-	fi
+        if getent passwd libvirt-qemu >/dev/null; then
+            deluser libvirt-qemu >/dev/null || true
+        fi
 
-    	if getent group libvirt-qemu >/dev/null; then
-    		delgroup libvirt-qemu >/dev/null || true
-	fi
+        if getent group libvirt-qemu >/dev/null; then
+            delgroup libvirt-qemu >/dev/null || true
+        fi
 
-	# Clean up logs and cached capabilities
-	rm -rf /var/log/libvirt \
-	       /var/cache/libvirt/qemu/capabilities
+        # Clean up logs and cached capabilities
+        rm -rf /var/log/libvirt \
+               /var/cache/libvirt/qemu/capabilities
 
-	# Clean up created dirs if existend and emtpy, they contain precious
-	# data otherwise
-	for dir in /var/lib/libvirt/qemu/save         \
-		   /var/lib/libvirt/qemu/snapshot         \
-		   /var/lib/libvirt/qemu/dump             \
-		   /var/lib/libvirt/qemu/nvram            \
-		   /var/lib/libvirt/qemu/ram/libvirt/qemu \
-		   /var/lib/libvirt/qemu/ram/libvirt      \
-		   /var/lib/libvirt/qemu/ram              \
-		   /var/lib/libvirt/qemu/channel          \
-		   /var/lib/libvirt/qemu                  \
-		   /var/cache/libvirt/qemu; do
-	    [ ! -d $dir ] || rmdir --ignore-fail-on-non-empty $dir
-	done
-    ;;
+        # Clean up created dirs if existend and emtpy, they contain precious
+        # data otherwise
+        for dir in /var/lib/libvirt/qemu/save \
+                   /var/lib/libvirt/qemu/snapshot \
+                   /var/lib/libvirt/qemu/dump \
+                   /var/lib/libvirt/qemu/nvram \
+                   /var/lib/libvirt/qemu/ram/libvirt/qemu \
+                   /var/lib/libvirt/qemu/ram/libvirt \
+                   /var/lib/libvirt/qemu/ram \
+                   /var/lib/libvirt/qemu/channel \
+                   /var/lib/libvirt/qemu \
+                   /var/cache/libvirt/qemu; do
+            [ ! -d $dir ] || rmdir --ignore-fail-on-non-empty $dir
+        done
+        ;;
     remove|upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
-    ;;
-
+        ;;
     *)
         echo "postrm called with unknown argument \`$1'" >&2
         exit 1
-    ;;
+        ;;
 esac
 
 # dh_installdeb will replace this with shell code automatically
@@ -67,5 +66,3 @@ esac
 #DEBHELPER#
 
 exit 0
-
-
diff --git a/debian/tests/smoke-qemu-session b/debian/tests/smoke-qemu-session
--- a/debian/tests/smoke-qemu-session
+++ b/debian/tests/smoke-qemu-session
@@ -8,23 +8,23 @@ DOMAIN=sqs
 
 cleanup()
 {
-   if [ -z "$CLEANED_UP" ]; then
-     virsh destroy sqs  || true
-     virsh undefine sqs || true
-     CLEANED_UP=1
-   fi
+    if [ -z "$CLEANED_UP" ]; then
+        virsh destroy sqs || true
+        virsh undefine sqs || true
+        CLEANED_UP=1
+    fi
 }
 
 trap cleanup EXIT
 
 if [ ! -f /vmlinuz ] || [ ! -f /initrd.img ]; then
-   echo "Kernel or initrd not found...skipping".
-   exit 77
+    echo "Kernel or initrd not found...skipping".
+    exit 77
 fi
 
 if [ $(uname -m) != "x86_64" ]; then
-   echo "Not on x86_64...skipping"
-   exit 77
+    echo "Not on x86_64...skipping"
+    exit 77
 fi
 
 echo echo "Running as $USER"
