postinst: Move user handling to daemon-driver-qemu
The "qemu" user/group is specific to the QEMU driver and it
should be handled by the corresponding package. This requires
moving the debconf templates too, since the prompt is related
to UID/GID allocation.

Gbp-Dch: Ignore

diff --git a/debian/libvirt-daemon-driver-qemu.postinst.in b/debian/libvirt-daemon-driver-qemu.postinst.in
--- a/debian/libvirt-daemon-driver-qemu.postinst.in
+++ b/debian/libvirt-daemon-driver-qemu.postinst.in
@@ -14,7 +14,52 @@ set -e
 # for details, see https://www.debian.org/doc/debian-policy/ or
 # the debian-policy package
 
+. /usr/share/debconf/confmodule
+
 #FINISH_CONFFILE_TRANSFER#
+
+# Allocated UID and GID for libvirt-qemu
+LIBVIRT_QEMU_UID=64055
+LIBVIRT_QEMU_GID=64055
+
+add_users_groups()
+{
+    if ! getent group kvm >/dev/null; then
+        addgroup --quiet --system kvm
+    fi
+    # user and group libvirt runs qemu/kvm instances with
+    if ! getent passwd libvirt-qemu >/dev/null; then
+
+        # set uid if available (expected); don't fail otherwise.
+        PARAMETER_UID=''
+        if ! getent passwd $LIBVIRT_QEMU_UID >/dev/null; then
+            PARAMETER_UID="--uid $LIBVIRT_QEMU_UID"
+        fi
+
+        adduser --quiet \
+                --system \
+                --ingroup kvm \
+                --quiet \
+                --disabled-login \
+                --disabled-password \
+                --home /var/lib/libvirt \
+                --no-create-home \
+                --gecos "Libvirt Qemu" \
+                $PARAMETER_UID \
+                libvirt-qemu
+    fi
+    if ! getent group libvirt-qemu >/dev/null; then
+
+        # set gid if available (expected); don't fail otherwise.
+        PARAMETER_GID=''
+        if ! getent group $LIBVIRT_QEMU_GID >/dev/null; then
+            PARAMETER_GID="--gid $LIBVIRT_QEMU_GID"
+        fi
+
+        addgroup --quiet --system $PARAMETER_GID libvirt-qemu
+        adduser --quiet libvirt-qemu libvirt-qemu
+    fi
+}
 
 add_statoverrides()
 {
@@ -57,6 +102,7 @@ DAEMON_SYSTEM_TO_DAEMON_DRIVER_QEMU="
 
 case "$1" in
     configure)
+        add_users_groups
         add_statoverrides
 
         # Make sure the log directory doesn't get removed on package removal
@@ -70,6 +116,9 @@ case "$1" in
         if [ -d /var/lib/libvirt/qemu/channel ]; then
             rmdir --ignore-fail-on-non-empty /var/lib/libvirt/qemu/channel
         fi
+
+        # Force refresh of capabilities (#731815)
+        rm -f /var/cache/libvirt/qemu/capabilities/*.xml
 
         for conf in $DAEMON_SYSTEM_TO_DAEMON_DRIVER_QEMU; do
             finish_conffile_transfer \
@@ -91,6 +140,8 @@ case "$1" in
         exit 1
     ;;
 esac
+
+db_stop
 
 #DEBHELPER#
 
